apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: {{control-plane-endpoint}}
    token: "{{control-plane-join-token}}"
    caCertHashes:
    - "{{control-plane-ca-cert-hash}}"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "{{node-ipv4}},{{node-ipv6}}"